name: docker-test
on: [push, pull_request]
jobs:
  test-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: docker build
      run: |
        docker build -f Dockerfile.dependencies . -t anarkiwi/gnuradio-dependencies:latest
        docker build --build-arg GNURADIO_TAG=main -t anarkiwi/gnuradio:latest -f Dockerfile .
